name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
      GO_VERSION: 1.21.8
    steps:
      - name: fetch feat-mocks branch
        run: |
          git clone --branch feat-mocks --depth 1 https://github.com/meowcraft-dev/arrow-adbc.git
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd arrow-adbc/go/adbc
          go test -exec "env LD_LIBRARY_PATH=$(pwd)/pkg/libabdc_driver_mocks.so" -v ./driver/mocks/...